bases:
- ../template/nodejs-ex-k

patches:
  - service_port.yaml
  - buildconfig.yaml 

# consumed with base's imagestream.yaml
images:
  - name: nodejs-ex # match images with this name
    newName: nodejs-dev # override the name